---
- name: Print out semaphore CI/CD vars
  hosts: localhost

  tasks:
  - name: Print out the vars
    ansible.builtin.debug:
      msg: "{{ semaphore_vars }}"
  - name: Print out the username
    ansible.builtin.debug:
      msg: "{{ semaphore_vars.task_details.username }}"